service: product-adjustment
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /products
          method: put
      - httpApi:
          path: /products/{id}
          method: put
